### PR TITLE
Migration from using creme to river 0.9.0

### PR DESCRIPTION
**Pull request by michhar**
This PR has updated `chantilly` to the usage of `river`, the evolved version of `creme`.

It is updated across the entire project, hence a very large set of changes.  Mainly, any reference to `creme` was simply changed to `river` and references to `fit_one`, changed to `learn_one`.  Tests ran successfully and the changelog was updated.  Please let me know if more updates are required or you have any comments.  The docker-compose example will not work correctly until a new version of `chantilly` is release to PyPI, however.

Additionally, I want to thank you for this awesome project.  I am working to deploy it using the docker-compose example to a VM in Azure and can add instructions at a later time.  Best Regards, Micheleen

### CODE REVIEW

**Comment by MaxHalford** [comment]
Hey there! This is so cool! I haven't been maintaining Chantilly because I'm working on something else (not available yet), but it's really great to make this work. I'll send a new release to PyPI.

**Comment by MaxHalford** [comment]
I've published a new release @michhar. 

By the way, feel free to get in touch as some point if you want to have a chat. I'd be curious to hear about how you're using Chantilly. 

All the best!

**Comment by MaxHalford** [comment]
Your profile is closed to me on LinkedIn, I'm not cool enough :)

**Comment by michhar** [comment]
> Your profile is closed to me on LinkedIn, I'm not cool enough :)

LOL.  Ok, I sent a connect your way!  Hopefully that works. :)

**Pull request merged**
